# -*- coding: utf-8 -*-

from osv import osv
from osv import fields

class OhealthHospitalProfile(osv.Model):
    _name = 'ohealth.hospital.profile'

    _columns = {
        'register_date': fields.date('Register Date', 
                                       help='Hospital Registration Date'),
        'hospital_name': fields.many2one('res.company', string='Hospital Name', required=False,
                            help='Hospital Name'),
        'hospital_code': fields.related('hospital_name','company_registry', readonly=True,type="char", string='Hospital Code'),
        'hospital_type': fields.selection([('rsu', 'General Hospital'), 
                                           ('rsj', 'Mental Hospital'),
                                           ('rsb', 'Maternity Hospital'),
                                           ('rsm', 'Eyes Hospital'),
                                           ('rsk', 'Cancer Hospital'),
                                           ('rstp','Pulmonary Tuberculosis Hospital'),
                                           ('rsl', 'Leprosy Hospital'),
                                           ('rsin','Infection Deseases Hospital'),
                                           ('rsortho', 'Orthopedic Hospital'),
                                           ('rsd', 'Deseases In Hospital'),
                                           ('rss', 'Surgical Hospital'),
                                           ('rsc', 'Cardiac Hospital'),
                                           ('rse', 'ENT Hospital'),
                                           ('rsst', 'Stroke Hospital'),
                                           ('rsmc', 'Mother and Child Hospital'),
                                           ('rsch', 'Child Hospital'),
                                           ('rsneu', 'Neurological Hospital'),
                                           ('rskid', 'Kidney Hospital'),
                                           ('rsdnn', 'Dental Hospital')], 
                                          'Hospital Type'),
        'hospital_class': fields.char(size=60,string='Hospital Class'),
        'kemenkes': fields.selection([('minofhealth','Ministry of Health'),
                                      ('tni','Army and Police')],
                                     'Kemenkes'),
        'kemenkes_class': fields.selection([('a','A'),
                                            ('b','B'),
                                            ('c','C'),
                                            ('nes','has not been established')],
                                           'Kemenkes Class'),
        'army_class': fields.selection([('1','1'),
                                            ('2','2'),
                                            ('3','3'),
                                            ('nes2','has not been established')],
                                           'Army Class'),
        'hospital_director': fields.char(size=60, string='Hospital Director'),
        'hospital_organizer': fields.char(size=60, string='Hospital Organizer'),
        'hospital_address': fields.related('hospital_name','street', type="char",readonly=True,string='Hospital Address'),
        'city': fields.related('hospital_name','city', type="char", readonly=True,string='City'),
        'zip': fields.related('hospital_name','zip', readonly=True,type="char",string='Zip'),
        'Phone': fields.related('hospital_name','phone', readonly=True,type="char",string='Phone'),
        'fax': fields.related('hospital_name','fax', readonly=True,type="char",string='Fax'),
        'email': fields.related('hospital_name','email', type="char",readonly=True,string='Email'),
        'pr_phone': fields.char(size=60,string='PR Phone', help='Phone number Hospital Public Relation or General Information'),
        'website': fields.related('hospital_name','website', type="char",readonly=True,string='Website'),
        'land_area': fields.char(size=60,string='Land Area'),
        'building_area': fields.char(size=60,string='Building Area'),
        'no_legal': fields.char(size=60,string='No. Legal'),
        'date_legal': fields.date('Legal Date'),
        'legal_by': fields.char(size=60,string='Legal Sign'),
        'legal_type': fields.char(size=60,string='Legal Type'),
        'legal_since': fields.char(size=60,string='Legal Since'),
        'private_hospital': fields.boolean('Private Hospital'),
        'status': fields.selection([('m','Moslem'),
                                    ('k','Catholic'),
                                    ('p','Protestant'),
                                    ('h','Hindu'),
                                    ('b','Budha'),
                                    ('so','Social Organization'),
                                    ('c','Company'),
                                    ('i','Individual')],
                                   'State'),
        'accreditation': fields.selection([('y','Yes'),
                                           ('n','No')],
                                          'Accreditation'),
        'phasing': fields.selection([('s5','Service 5'),
                                     ('s12','Service 12'),
                                     ('s16','Service 16'),
                                     ('ia','International Accreditation')],
                                    'Phasing'),
        'accred_status': fields.selection([('f','Full'),
                                           ('c','Conditional'),
                                           ('fl','Failed')],
                                          'Accreditation Status'),
        'accred_date': fields.char(size=60,string='Accreditation Date'),
        'bed_number': fields.char(size=60,string='Bed Number'),
        'perinatologi_bed': fields.char(size=60,string='Perinatologi Bed'),
        'vvip_bed': fields.char(size=60,string='VVIP bed'),
        'vip': fields.char(size=60,string='VIP bed'),
        'class_1': fields.char(size=60,string='I bed'),
        'class_2': fields.char(size=60,string='II Bed'),
        'class_3': fields.char(size=60,string='III Bed'),
        'class_icu': fields.char(size=60,string='ICU Bed'),
        'class_picu': fields.char(size=60,string='NICU Bed'),
        'class_nicu': fields.char(size=60,string='PICU'),
        'class_hcu': fields.char(size=60,string='HCU'),
        'class_iccu': fields.char(size=60,string='ICCU'),
        'isolation_room': fields.char(size=60,string='Isolation Room'),
        'emergency_room': fields.char(size=60,string='Emergency Room'),
        'parenatal_room': fields.char(size=60,string='Parenatal Room'),
        'operation_room': fields.char(size=60,string='Operation Room'),
        'spa': fields.char(size=60,string='Sp.A Number'),
        'spog': fields.char(size=60,string='Sp.OG'),
        'sppd': fields.char(size=60,string='Sp.Pd'),
        'spb': fields.char(size=60,string='Sp.B'),
        'sprad': fields.char(size=60,string='Sp.Rad'),
        'sprm': fields.char(size=60,string='Sp.RM'),
        'span': fields.char(size=60,string='Sp.An'),
        'spjp': fields.char(size=60,string='Sp.JP'),
        'spm': fields.char(size=60,string='Sp.M'),
        'sptht': fields.char(size=60,string='Sp.THT'),
        'spkj': fields.char(size=60,string='Sp.KJ'),
        'spp': fields.char(size=60,string='Sp.P'),
        'sppk': fields.char(size=60,string='Sp.PK'),
        'sppd2': fields.char(size=60,string='Sp.PD'),
        'sps': fields.char(size=60,string='Sp.S'),
        'sub_spes': fields.char(size=60,string='Other Sub. Specialist'),
        'other_spes': fields.char(size=60,string='Other Specialist'),
        'general_doctor': fields.char(size=60,string='General Doctor'),
        'nutrient_doctor': fields.char(size=60,string='Nutrient Doctor'),
        'nurse': fields.char(size=60,string='Nurse'),
        'midwife': fields.char(size=60,string='Midwife'),
        'pharmacy': fields.char(size=60,string='Pharmacy'),
        'other_health_practician': fields.char(size=60,string='Other Health practician'),
        'non_medic': fields.char(size=60,string='Non Medical Practician'),
        'extra_info': fields.text(string='Extra Info'),
    }
    
OhealthHospitalProfile()